=encoding utf-8

=head1 NÉV

ToolbarTicketNumberSearch - jegyszámok keresése az eszköztáron

=head1 LEÍRÁS

Egy keresőmező az eszköztárhoz, amely a jegyszámra keres rá.

=head1 KÓDTÁROLÓ ÉS HIBAKÖVETŐ

A kódtároló és a hibakövető a L<https://github.com/reneeb/otrs-ToolbarTicketNumberSearch>
címen érhető el.

=head1 SZERZŐ ÉS LICENC

Ezt a csomagot Renée Bäcker E<lt>otrs@perl-services.deE<gt> írta.

A csomag az AGPL feltételei szerint licencelt. Ha nem kapta meg ezt a fájlt, 
akkor nézze meg a L<http://www.gnu.org/licenses/agpl.txt> címen.

=head1 MAGYAR FORDÍTÁS

A magyar fordítást az OTRS-megoldások csapata készítette.
Copyright (C) 2016 Úr Balázs, L<http://otrs-megoldasok.hu>
